package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String cedula;
     private String direccion;
     private String correoElectronico;
     private String telefono;
     private float descuentoPorcentual;
     private boolean estado;
     private Set ventaClienteNaturals = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String primerNombre, String segundoNombre, String primerApellido, String cedula, String direccion, String correoElectronico, String telefono, float descuentoPorcentual, boolean estado) {
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.primerApellido = primerApellido;
        this.cedula = cedula;
        this.direccion = direccion;
        this.correoElectronico = correoElectronico;
        this.telefono = telefono;
        this.descuentoPorcentual = descuentoPorcentual;
        this.estado = estado;
    }
    public Cliente(String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String cedula, String direccion, String correoElectronico, String telefono, float descuentoPorcentual, boolean estado, Set ventaClienteNaturals) {
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.cedula = cedula;
       this.direccion = direccion;
       this.correoElectronico = correoElectronico;
       this.telefono = telefono;
       this.descuentoPorcentual = descuentoPorcentual;
       this.estado = estado;
       this.ventaClienteNaturals = ventaClienteNaturals;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public float getDescuentoPorcentual() {
        return this.descuentoPorcentual;
    }
    
    public void setDescuentoPorcentual(float descuentoPorcentual) {
        this.descuentoPorcentual = descuentoPorcentual;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getVentaClienteNaturals() {
        return this.ventaClienteNaturals;
    }
    
    public void setVentaClienteNaturals(Set ventaClienteNaturals) {
        this.ventaClienteNaturals = ventaClienteNaturals;
    }




}


