package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1



/**
 * CodigoBarra generated by hbm2java
 */
public class CodigoBarra  implements java.io.Serializable {


     private String idCodigoBarra;
     private Producto producto;

    public CodigoBarra() {
    }

    public CodigoBarra(String idCodigoBarra, Producto producto) {
       this.idCodigoBarra = idCodigoBarra;
       this.producto = producto;
    }
   
    public String getIdCodigoBarra() {
        return this.idCodigoBarra;
    }
    
    public void setIdCodigoBarra(String idCodigoBarra) {
        this.idCodigoBarra = idCodigoBarra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }




}


