package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idcompra;
     private Empleados empleados;
     private Vendedores vendedores;
     private String noFactura;
     private Date fechaCompra;
     private String tipoFactura;
     private String moneda;
     private boolean pagado;
     private boolean anulado;
     private Set detalleCompras = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Empleados empleados, Vendedores vendedores, String noFactura, Date fechaCompra, String tipoFactura, String moneda, boolean pagado, boolean anulado) {
        this.empleados = empleados;
        this.vendedores = vendedores;
        this.noFactura = noFactura;
        this.fechaCompra = fechaCompra;
        this.tipoFactura = tipoFactura;
        this.moneda = moneda;
        this.pagado = pagado;
        this.anulado = anulado;
    }
    public Compra(Empleados empleados, Vendedores vendedores, String noFactura, Date fechaCompra, String tipoFactura, String moneda, boolean pagado, boolean anulado, Set detalleCompras) {
       this.empleados = empleados;
       this.vendedores = vendedores;
       this.noFactura = noFactura;
       this.fechaCompra = fechaCompra;
       this.tipoFactura = tipoFactura;
       this.moneda = moneda;
       this.pagado = pagado;
       this.anulado = anulado;
       this.detalleCompras = detalleCompras;
    }
   
    public Integer getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(Integer idcompra) {
        this.idcompra = idcompra;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }
    public String getNoFactura() {
        return this.noFactura;
    }
    
    public void setNoFactura(String noFactura) {
        this.noFactura = noFactura;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }
    public boolean isAnulado() {
        return this.anulado;
    }
    
    public void setAnulado(boolean anulado) {
        this.anulado = anulado;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


