package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private Integer iddetalle;
     private Producto producto;
     private Venta venta;
     private float cantidadProducto;
     private float bonificacion;
     private float precioUnitario;
     private float iva;
     private float descuento;
     private Set devolucionVentas = new HashSet(0);

    public DetalleFactura() {
    }

	
    public DetalleFactura(Producto producto, Venta venta, float cantidadProducto, float bonificacion, float precioUnitario, float iva, float descuento) {
        this.producto = producto;
        this.venta = venta;
        this.cantidadProducto = cantidadProducto;
        this.bonificacion = bonificacion;
        this.precioUnitario = precioUnitario;
        this.iva = iva;
        this.descuento = descuento;
    }
    public DetalleFactura(Producto producto, Venta venta, float cantidadProducto, float bonificacion, float precioUnitario, float iva, float descuento, Set devolucionVentas) {
       this.producto = producto;
       this.venta = venta;
       this.cantidadProducto = cantidadProducto;
       this.bonificacion = bonificacion;
       this.precioUnitario = precioUnitario;
       this.iva = iva;
       this.descuento = descuento;
       this.devolucionVentas = devolucionVentas;
    }
   
    public Integer getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(Integer iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public float getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(float cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public float getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(float bonificacion) {
        this.bonificacion = bonificacion;
    }
    public float getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(float precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    public float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(float descuento) {
        this.descuento = descuento;
    }
    public Set getDevolucionVentas() {
        return this.devolucionVentas;
    }
    
    public void setDevolucionVentas(Set devolucionVentas) {
        this.devolucionVentas = devolucionVentas;
    }




}


