package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  implements java.io.Serializable {


     private Integer idDetalleCompra;
     private Compra compra;
     private Producto producto;
     private float cantidadProducto;
     private float bonificacion;
     private float precioUnitario;
     private float descuento;
     private float iva;
     private Set devolucionCompras = new HashSet(0);

    public DetalleCompra() {
    }

	
    public DetalleCompra(Compra compra, Producto producto, float cantidadProducto, float bonificacion, float precioUnitario, float descuento, float iva) {
        this.compra = compra;
        this.producto = producto;
        this.cantidadProducto = cantidadProducto;
        this.bonificacion = bonificacion;
        this.precioUnitario = precioUnitario;
        this.descuento = descuento;
        this.iva = iva;
    }
    public DetalleCompra(Compra compra, Producto producto, float cantidadProducto, float bonificacion, float precioUnitario, float descuento, float iva, Set devolucionCompras) {
       this.compra = compra;
       this.producto = producto;
       this.cantidadProducto = cantidadProducto;
       this.bonificacion = bonificacion;
       this.precioUnitario = precioUnitario;
       this.descuento = descuento;
       this.iva = iva;
       this.devolucionCompras = devolucionCompras;
    }
   
    public Integer getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(Integer idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public float getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(float cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public float getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(float bonificacion) {
        this.bonificacion = bonificacion;
    }
    public float getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(float precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(float descuento) {
        this.descuento = descuento;
    }
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    public Set getDevolucionCompras() {
        return this.devolucionCompras;
    }
    
    public void setDevolucionCompras(Set devolucionCompras) {
        this.devolucionCompras = devolucionCompras;
    }




}


