package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DevolucionVenta generated by hbm2java
 */
public class DevolucionVenta  implements java.io.Serializable {


     private Integer iddevolucionVenta;
     private DetalleFactura detalleFactura;
     private Date fechaDevolucion;
     private String observaciones;
     private float cantidad;

    public DevolucionVenta() {
    }

    public DevolucionVenta(DetalleFactura detalleFactura, Date fechaDevolucion, String observaciones, float cantidad) {
       this.detalleFactura = detalleFactura;
       this.fechaDevolucion = fechaDevolucion;
       this.observaciones = observaciones;
       this.cantidad = cantidad;
    }
   
    public Integer getIddevolucionVenta() {
        return this.iddevolucionVenta;
    }
    
    public void setIddevolucionVenta(Integer iddevolucionVenta) {
        this.iddevolucionVenta = iddevolucionVenta;
    }
    public DetalleFactura getDetalleFactura() {
        return this.detalleFactura;
    }
    
    public void setDetalleFactura(DetalleFactura detalleFactura) {
        this.detalleFactura = detalleFactura;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }




}


