package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DevolucionCompra generated by hbm2java
 */
public class DevolucionCompra  implements java.io.Serializable {


     private Integer iddevolucionCompra;
     private DetalleCompra detalleCompra;
     private Date fechaDevolucion;
     private String observaciones;
     private float cantidadDevolucion;

    public DevolucionCompra() {
    }

    public DevolucionCompra(DetalleCompra detalleCompra, Date fechaDevolucion, String observaciones, float cantidadDevolucion) {
       this.detalleCompra = detalleCompra;
       this.fechaDevolucion = fechaDevolucion;
       this.observaciones = observaciones;
       this.cantidadDevolucion = cantidadDevolucion;
    }
   
    public Integer getIddevolucionCompra() {
        return this.iddevolucionCompra;
    }
    
    public void setIddevolucionCompra(Integer iddevolucionCompra) {
        this.iddevolucionCompra = iddevolucionCompra;
    }
    public DetalleCompra getDetalleCompra() {
        return this.detalleCompra;
    }
    
    public void setDetalleCompra(DetalleCompra detalleCompra) {
        this.detalleCompra = detalleCompra;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public float getCantidadDevolucion() {
        return this.cantidadDevolucion;
    }
    
    public void setCantidadDevolucion(float cantidadDevolucion) {
        this.cantidadDevolucion = cantidadDevolucion;
    }




}


