package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos  implements java.io.Serializable {


     private Integer idPago;
     private Cambio cambio;
     private Venta venta;
     private Date fechaPago;
     private float monto;
     private String moneda;
     private String metodoPago;

    public Pagos() {
    }

    public Pagos(Cambio cambio, Venta venta, Date fechaPago, float monto, String moneda, String metodoPago) {
       this.cambio = cambio;
       this.venta = venta;
       this.fechaPago = fechaPago;
       this.monto = monto;
       this.moneda = moneda;
       this.metodoPago = metodoPago;
    }
   
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
    public Cambio getCambio() {
        return this.cambio;
    }
    
    public void setCambio(Cambio cambio) {
        this.cambio = cambio;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public float getMonto() {
        return this.monto;
    }
    
    public void setMonto(float monto) {
        this.monto = monto;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }




}


