package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private Categorias categorias;
     private byte[] foto;
     private String nombre;
     private float precioVenta;
     private float precioInventario;
     private String tipoVenta;
     private float cantidadMinima;
     private float cantidadInventario;
     private String descripcion;
     private boolean iva;
     private boolean estado;
     private Set detalleCompras = new HashSet(0);
     private Set codigoBarras = new HashSet(0);
     private Set detalleFacturas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Categorias categorias, String nombre, float precioVenta, float precioInventario, float cantidadMinima, float cantidadInventario, String descripcion, boolean iva, boolean estado) {
        this.categorias = categorias;
        this.nombre = nombre;
        this.precioVenta = precioVenta;
        this.precioInventario = precioInventario;
        this.cantidadMinima = cantidadMinima;
        this.cantidadInventario = cantidadInventario;
        this.descripcion = descripcion;
        this.iva = iva;
        this.estado = estado;
    }
    public Producto(Categorias categorias, byte[] foto, String nombre, float precioVenta, float precioInventario, String tipoVenta, float cantidadMinima, float cantidadInventario, String descripcion, boolean iva, boolean estado, Set detalleCompras, Set codigoBarras, Set detalleFacturas) {
       this.categorias = categorias;
       this.foto = foto;
       this.nombre = nombre;
       this.precioVenta = precioVenta;
       this.precioInventario = precioInventario;
       this.tipoVenta = tipoVenta;
       this.cantidadMinima = cantidadMinima;
       this.cantidadInventario = cantidadInventario;
       this.descripcion = descripcion;
       this.iva = iva;
       this.estado = estado;
       this.detalleCompras = detalleCompras;
       this.codigoBarras = codigoBarras;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(float precioVenta) {
        this.precioVenta = precioVenta;
    }
    public float getPrecioInventario() {
        return this.precioInventario;
    }
    
    public void setPrecioInventario(float precioInventario) {
        this.precioInventario = precioInventario;
    }
    public String getTipoVenta() {
        return this.tipoVenta;
    }
    
    public void setTipoVenta(String tipoVenta) {
        this.tipoVenta = tipoVenta;
    }
    public float getCantidadMinima() {
        return this.cantidadMinima;
    }
    
    public void setCantidadMinima(float cantidadMinima) {
        this.cantidadMinima = cantidadMinima;
    }
    public float getCantidadInventario() {
        return this.cantidadInventario;
    }
    
    public void setCantidadInventario(float cantidadInventario) {
        this.cantidadInventario = cantidadInventario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isIva() {
        return this.iva;
    }
    
    public void setIva(boolean iva) {
        this.iva = iva;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }
    public Set getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(Set codigoBarras) {
        this.codigoBarras = codigoBarras;
    }
    public Set getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


