package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer idproveedor;
     private String nombre;
     private String ruc;
     private String direccion;
     private String telefono;
     private String correoElectronico;
     private Boolean estado;
     private Set vendedoreses = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(String direccion) {
        this.direccion = direccion;
    }
    public Proveedores(String nombre, String ruc, String direccion, String telefono, String correoElectronico, Boolean estado, Set vendedoreses) {
       this.nombre = nombre;
       this.ruc = ruc;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correoElectronico = correoElectronico;
       this.estado = estado;
       this.vendedoreses = vendedoreses;
    }
   
    public Integer getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(Integer idproveedor) {
        this.idproveedor = idproveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getVendedoreses() {
        return this.vendedoreses;
    }
    
    public void setVendedoreses(Set vendedoreses) {
        this.vendedoreses = vendedoreses;
    }




}


