package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer noFactura;
     private Empleados empleados;
     private Date fechaVenta;
     private String tipoFactura;
     private boolean excentoIva;
     private String observaciones;
     private boolean anulado;
     private String estado;
     private Set ventaClienteJuridicos = new HashSet(0);
     private Set contratoCreditos = new HashSet(0);
     private Set ventaClienteNaturals = new HashSet(0);
     private Set detalleFacturas = new HashSet(0);
     private Set pagoses = new HashSet(0);
     private Set ventaCreditos = new HashSet(0);

    public Venta() {
    }

	
    public Venta(Empleados empleados, Date fechaVenta, String tipoFactura, boolean excentoIva, boolean anulado, String estado) {
        this.empleados = empleados;
        this.fechaVenta = fechaVenta;
        this.tipoFactura = tipoFactura;
        this.excentoIva = excentoIva;
        this.anulado = anulado;
        this.estado = estado;
    }
    public Venta(Empleados empleados, Date fechaVenta, String tipoFactura, boolean excentoIva, String observaciones, boolean anulado, String estado, Set ventaClienteJuridicos, Set contratoCreditos, Set ventaClienteNaturals, Set detalleFacturas, Set pagoses, Set ventaCreditos) {
       this.empleados = empleados;
       this.fechaVenta = fechaVenta;
       this.tipoFactura = tipoFactura;
       this.excentoIva = excentoIva;
       this.observaciones = observaciones;
       this.anulado = anulado;
       this.estado = estado;
       this.ventaClienteJuridicos = ventaClienteJuridicos;
       this.contratoCreditos = contratoCreditos;
       this.ventaClienteNaturals = ventaClienteNaturals;
       this.detalleFacturas = detalleFacturas;
       this.pagoses = pagoses;
       this.ventaCreditos = ventaCreditos;
    }
   
    public Integer getNoFactura() {
        return this.noFactura;
    }
    
    public void setNoFactura(Integer noFactura) {
        this.noFactura = noFactura;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public boolean isExcentoIva() {
        return this.excentoIva;
    }
    
    public void setExcentoIva(boolean excentoIva) {
        this.excentoIva = excentoIva;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public boolean isAnulado() {
        return this.anulado;
    }
    
    public void setAnulado(boolean anulado) {
        this.anulado = anulado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVentaClienteJuridicos() {
        return this.ventaClienteJuridicos;
    }
    
    public void setVentaClienteJuridicos(Set ventaClienteJuridicos) {
        this.ventaClienteJuridicos = ventaClienteJuridicos;
    }
    public Set getContratoCreditos() {
        return this.contratoCreditos;
    }
    
    public void setContratoCreditos(Set contratoCreditos) {
        this.contratoCreditos = contratoCreditos;
    }
    public Set getVentaClienteNaturals() {
        return this.ventaClienteNaturals;
    }
    
    public void setVentaClienteNaturals(Set ventaClienteNaturals) {
        this.ventaClienteNaturals = ventaClienteNaturals;
    }
    public Set getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }
    public Set getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }
    public Set getVentaCreditos() {
        return this.ventaCreditos;
    }
    
    public void setVentaCreditos(Set ventaCreditos) {
        this.ventaCreditos = ventaCreditos;
    }




}


