package POJO;
// Generated 07-06-2015 07:05:42 PM by Hibernate Tools 4.3.1



/**
 * VentaClienteNatural generated by hbm2java
 */
public class VentaClienteNatural  implements java.io.Serializable {


     private Integer idFacturaClienteNatural;
     private Cliente cliente;
     private Venta venta;

    public VentaClienteNatural() {
    }

    public VentaClienteNatural(Cliente cliente, Venta venta) {
       this.cliente = cliente;
       this.venta = venta;
    }
   
    public Integer getIdFacturaClienteNatural() {
        return this.idFacturaClienteNatural;
    }
    
    public void setIdFacturaClienteNatural(Integer idFacturaClienteNatural) {
        this.idFacturaClienteNatural = idFacturaClienteNatural;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }




}


